from app import extract_data_kuwait, extract_data_malaysia

print('=' * 80)
print('KUWAIT3 - Domestic Flight')
print('=' * 80)
k3 = extract_data_kuwait('kuwait3.pdf')
print(f'Ticket Number: {k3["Ticket Number"]}')
print(f'CGST: {k3["CGST"]}')
print(f'SGST: {k3["SGST"]}')
print(f'IGST: {k3["IGST"]}')
print(f'Tax Summary: {k3["Tax Summary"]}')

print('\n' + '=' * 80)
print('KUWAIT4 - International Flight')
print('=' * 80)
k4 = extract_data_kuwait('kuwait4.pdf')
print(f'Ticket Number: {k4["Ticket Number"]}')
print(f'CGST: {k4["CGST"]}')
print(f'SGST: {k4["SGST"]}')
print(f'IGST: {k4["IGST"]}')
print(f'Tax Summary: {k4["Tax Summary"]}')

print('\n' + '=' * 80)
print('MALAYSIA6 - Domestic Flight')
print('=' * 80)
m6 = extract_data_malaysia('malaysia6.PDF')
print(f'Ticket Number: {m6["Ticket Number"]}')
print(f'CGST: {m6["CGST"]}')
print(f'SGST: {m6["SGST"]}')
print(f'IGST: {m6["IGST"]}')
print(f'Tax Summary: {m6["Tax Summary"]}')

print('\n' + '=' * 80)
print('SUMMARY')
print('=' * 80)
print(f'Kuwait3: {k3["Tax Summary"]}')
print(f'Kuwait4: {k4["Tax Summary"]}')
print(f'Malaysia6: {m6["Tax Summary"]}')
